### ISSUE TITLE
Possible bug: iRODS::find_objects_by_meta 

### ISSUE THREAD

**Issue by jwhsanger** [wtsi-npg/perl-irods-wrap#20]
I think...

If I have the following iRODS paths with metadata:

/test/manifest/my_manifest.txt {file_type: 'txt'}
/test/manifest_processed/my_manifest.txt {file_type: 'txt'}

The following code:
my @files = irods->find_objects_by_meta( '/test/manifest', 'txt' );

will return both:
(
  '/test/manifest/my_manifest.txt',
  '/test/manifest_processed/my_manifest.txt'
)

The offending line of code:
....
 return grep { /^$root/msx } @sorted;

If the path dosnt have a trailing slash the pattern match will match it against collections with the same prefix. If I have understood this properly, either this is unwanted behaviour or should be explained in the docs as a feature :)

Cheers
Jon

**Comment by keithj** [comment]
I think that this may be a bug because the docs and tests illustrate only cases where the path isn't partial. However, the correct behaviour has never been well defined. I think it makes sense for the method to ensure a trailing slash is there so that, for example:

````
$irods->find_objects_by_meta( '/test/manifest_proc', ['type' => 'txt']);
````

becomes equivalent to

````
$irods->find_objects_by_meta( '/test/manifest_proc/', ['type' => 'txt']);
````

and returns nothing.

In cases where the caller wants to do further filtering on partial paths, they can.

**Comment by jwhsanger** [comment]
I think adding something like this would solve the problem:

## Ensure single trailing slash
  $root =~ s/\/*$/\//;

return grep { /^$root/msx } @sorted;
