### ISSUE TITLE
Review use of RabbitMQ

### ISSUE THREAD

**Issue by kjsanger** [wtsi-npg/perl-irods-wrap#213]
Do we still need this functionality?

**Comment by mgcam** [comment]
> Do we still need this functionality?
>
As far as I remember, this feature has not been finished. Even if it 
were, I would be hesitant to use it since it add complexity to iRODS 
Perl API calls, which are already complex.




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by kjsanger** [comment]
Closed by #222 and #226
