### ISSUE TITLE
Feature Request Object/Collection time stamp

### ISSUE THREAD

**Issue by jwhsanger** [wtsi-npg/perl-irods-wrap#22]
Hi Guys,

I couldnt find this functionality so forgive me if it already exists. It would be nice to be able pull back the created/last modified time stamp for an object or collection. This would be useful to determine when a file has entered iRODS or how far apart a pair of lane bams have been dropped when making the consideration to proceed with processing or not.... for example.

Looking at the code base this dosnt seem like a simple request, but I thought I would ask.

Many thanks,
Jon

**Comment by keithj** [comment]
Hi Jon,

baton does support extracting the internal created and modified timestamps from the ICAT database. However, this isn't exposed in the Perl wrapper because they are the timestamps of the individual replicates rather than of the abstract "data object" entity and therefore of limited use.

For example, a "created" timestamp on a data object should be immutable. The "created" timestamps of replicates that constitute a data object can be "walked" forwards in time by deleting and recreating individual replicates e.g. by a systems administrator managing disk space, resources or other egitimate non-experimental intervention. You also have the complication of there being e.g. 2 "created" timestamps if there are 2 replicates.

This is a design limit of iRODS itself - there should really be an additional timestamp of abstract data objects.

We work around this problem by adding timestamps in the metadata.

Keith

**Comment by jwhsanger** [comment]
Hi Keith,

Thanks for the reply - it makes sense from an 'Object' point of view and I can see how the ICAT time stamp might be misleading. Working through my use case this functionality would have been useful as I am trying to ascertain when an object appears in a collection not necessarily when the object was created.

I am currently using baton for a work around but I have now broken my nicely encapsulated application structure :-) 

I guess this would be a low priority feature request but it would be nice it could be exposed. When I have time I will see if I can provide a pull request with something sensible for you to consider.

Cheers
Jon
