### ISSUE TITLE
Possible bug: iRODS::copy_object

### ISSUE THREAD

**Issue by jwhsanger** [wtsi-npg/perl-irods-wrap#24]
Hi Guys,

I have noticed some unusual behaviour in the above method. If you supply the target as a collection (dir) with a trailing slash, it will copy the source object to the target collection but will assign the AVUs to the collection instead of the new object.

Obvious work around is to qualify the whole target object path, however this might catch a few people out.

Cheers
Jon,

**Comment by keithj** [comment]
Hi Jon,

That looks like a bug to me. Trickiness with respect to trailing slashes is something I want to avoid in the API.

**Comment by keithj** [comment]
I've confirmed this behaviour. `WTSI::NPG::iRODS::copy_object` takes two absolute data object paths, so by passing a collection path as the second argument you're getting undefined behaviour. Underneath it invokes `icp`, which does accept a  collection path as the second argument, so the object does get copied.

I need to tighten the argument checking so that an exception is raised when this happens. This will mean testing each path on the server to see whether it is a data object or collection (it's not possible to from path strings to distinguish a data object from a collection without trailing slash). Hopefully this will not affect performance too much.

**Comment by keithj** [comment]
I've added the checks now, so it shouldn't be possible to copy a data object into a collection unless the full path of the target is given.
