### ISSUE TITLE
Feature Request: IRODS::get_object

### ISSUE THREAD

**Issue by jwhsanger** [wtsi-npg/perl-irods-wrap#51]
Yes I know, my feature requests seem to be a bit inane but here is another one for you:

Would it be possible to allow additional args to be passed to the iget command?

e.g. irods->get_object('my/irods/object', 'my/out/location', '-K', '-Q' ...)

This would let me fine tune the behaviour of the iget command from within the api.

Is this a logical suggestion??

Cheers
Jon

**Comment by keithj** [comment]
The concern I have is that these arguments will prevent us from changing the backend "getting" program. That is likely to happen because I've already written `baton-get` to replace `iget` in some
circumstances. We want to be able to switch backends dynamically.

I would suggest overriding the `get_object` method with one that passes its extra arguments to the
backend. That way, even when we switch backends in the library, your code will go on working.
